# Loading data and do EDA(Exploratory Data Analysis)

kaggle page: https://www.kaggle.com/t/88c20ee1a8ec43c8b155278f5d590602

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('HR-Employee-Attrition_train.csv')
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1365   36        No  Travel_Frequently        884  Research & Development   
1366   39        No      Travel_Rarely        613  Research & Development   
1367   27        No      Travel_Rarely        155  Research & Development   
1368   49        No  Travel_Frequently       1023                   Sales   
1369   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1365                23          2        Medical              1   
1366                 6          1        Medical              1   
1367                 4          3  Life Sciences              1   
1368                 2          3        Medical              1   
1369                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1365            2061  ...                         3            80   
1366            2062  ...                         1            80   
1367            2064  ...                         2            80   
1368            2065  ...                         4            80   
1369            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1365                 1                 17                      3   
1366                 1                  9                      5   
1367                 1                  6                      0   
1368                 0                 17                      3   
1369                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1365               3               5                  2   
1366               3               7                  7   
1367               3               6                  2   
1368               2               9    

In [2]:
df["Attrition"]

0       Yes
1        No
2       Yes
3        No
4        No
       ... 
1365     No
1366     No
1367     No
1368     No
1369     No
Name: Attrition, Length: 1370, dtype: object

In [3]:
# check if there is any missing value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1370 non-null   int64 
 1   Attrition                 1370 non-null   object
 2   BusinessTravel            1370 non-null   object
 3   DailyRate                 1370 non-null   int64 
 4   Department                1370 non-null   object
 5   DistanceFromHome          1370 non-null   int64 
 6   Education                 1370 non-null   int64 
 7   EducationField            1370 non-null   object
 8   EmployeeCount             1370 non-null   int64 
 9   EmployeeNumber            1370 non-null   int64 
 10  EnvironmentSatisfaction   1370 non-null   int64 
 11  Gender                    1370 non-null   object
 12  HourlyRate                1370 non-null   int64 
 13  JobInvolvement            1370 non-null   int64 
 14  JobLevel                

In [4]:
# Check numerical data columns
print('There are %s numerical columns.'%(str(len(df.select_dtypes(include=['int64']).columns))))
df.select_dtypes(include=['int64']).columns

There are 26 numerical columns.


Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [5]:
# check categorical data columns 
print('There are %s categorical columns.'%(str(len(df.select_dtypes(include=['object']).columns))))
df.select_dtypes(include=['object']).columns

There are 9 categorical columns.


Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'Over18', 'OverTime'],
      dtype='object')

We can further divide these 35 columns into 4 groups.

In [6]:
id_col = 'EmployeeNumber'

target_col = 'Attrition'

# 25 numerical_cols
numerical_cols = ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EnvironmentSatisfaction', 
                'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 
                'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 
                'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 
                'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

# 8 categorical_cols
categorical_cols = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 
                 'Over18', 'OverTime']

In [7]:
# check 8 categorical columns
nunique_values = []
na_values = []

for col in categorical_cols:
    nunique_values.append(df[col].nunique())
    na_values.append(len(df.loc[df[col].isna()]))

df_stats_categorical = pd.DataFrame(list(zip(categorical_cols,nunique_values,na_values)),columns=['Column_Name','#Unique_Values','#Null_Value'])
df_stats_categorical

Column_Name  #Unique_Values  #Null_Value
0  BusinessTravel               3            0
1      Department               3            0
2  EducationField               6            0
3          Gender               2            0
4         JobRole               9            0
5   MaritalStatus               3            0
6          Over18               1            0
7        OverTime               2            0

In [8]:
# check Null columns
df_stats_categorical[df_stats_categorical['#Null_Value'] > 0]

Empty DataFrame
Columns: [Column_Name, #Unique_Values, #Null_Value]
Index: []

In [9]:
# check columns with only 1 value
df_stats_categorical[df_stats_categorical['#Unique_Values'] == 1]

Column_Name  #Unique_Values  #Null_Value
6      Over18               1            0

The column 'Over18' only contains 1 unique value, therefore we could drop it.

In [10]:
# check 25 numerical columns
na_values = []

for col in numerical_cols:
    na_values.append(len(df.loc[df[col].isna()]))

df_stats_numerical = pd.DataFrame(list(zip(numerical_cols,na_values)),columns=['Column_Name','#Null_Value'])
df_stats_numerical

Column_Name  #Null_Value
0                        Age            0
1                  DailyRate            0
2           DistanceFromHome            0
3                  Education            0
4              EmployeeCount            0
5    EnvironmentSatisfaction            0
6                 HourlyRate            0
7             JobInvolvement            0
8                   JobLevel            0
9            JobSatisfaction            0
10             MonthlyIncome            0
11               MonthlyRate            0
12        NumCompaniesWorked            0
13         PercentSalaryHike            0
14         PerformanceRating            0
15  RelationshipSatisfaction            0
16             StandardHours            0
17          StockOptionLevel            0
18         TotalWorkingYears            0
19     TrainingTimesLastYear            0
20           WorkLifeBalance            0
21            YearsAtCompany            0
22        YearsInCurrentRole            0
23   YearsSinceLastPromotion            0
24      YearsWithCurrManager            0

In [11]:
# check Null columns
df_stats_numerical[df_stats_numerical['#Null_Value'] > 0]

Empty DataFrame
Columns: [Column_Name, #Null_Value]
Index: []

In [12]:
# Transpose the numerical data
df_stats = df[numerical_cols].describe().T
df_stats

count          mean          std     min     25%  \
Age                       1370.0     36.927737     9.163392    18.0    30.0   
DailyRate                 1370.0    803.920438   402.834234   102.0   465.0   
DistanceFromHome          1370.0      9.260584     8.135717     1.0     2.0   
Education                 1370.0      2.918978     1.022753     1.0     2.0   
EmployeeCount             1370.0      1.000000     0.000000     1.0     1.0   
EnvironmentSatisfaction   1370.0      2.728467     1.097507     1.0     2.0   
HourlyRate                1370.0     65.845255    20.308706    30.0    48.0   
JobInvolvement            1370.0      2.723358     0.719220     1.0     2.0   
JobLevel                  1370.0      2.067153     1.110354     1.0     1.0   
JobSatisfaction           1370.0      2.727737     1.102307     1.0     2.0   
MonthlyIncome             1370.0   6521.051095  4715.993876  1009.0  2909.5   
MonthlyRate               1370.0  14284.823358  7115.574627  2094.0  8001.0   
NumCompaniesWorked        1370.0      2.700730     2.503949     0.0     1.0   
PercentSalaryHike         1370.0     15.212409     3.650669    11.0    12.0   
PerformanceRating         1370.0      3.151825     0.358982     3.0     3.0   
RelationshipSatisfaction  1370.0      2.702190     1.080572     1.0     2.0   
StandardHours             1370.0     80.000000     0.000000    80.0    80.0   
StockOptionLevel          1370.0      0.793431     0.845450     0.0     0.0   
TotalWorkingYears         1370.0     11.280292     7.788023     0.0     6.0   
TrainingTimesLastYear     1370.0      2.805109     1.300942     0.0     2.0   
WorkLifeBalance           1370.0      2.765693     0.700510     1.0     2.0   
YearsAtCompany            1370.0      6.986861     6.135181     0.0     3.0   
YearsInCurrentRole        1370.0      4.218248     3.609878     0.0     2.0   
YearsSinceLastPromotion   1370.0      2.182482     3.224312     0.0     0.0   
YearsWithCurrManager      1370.0      4.130657     3.591201     0.0     2.0   

                              50%       75%      max  
Age                          36.0     43.00     60.0  
DailyRate                   806.5   1156.00   1499.0  
DistanceFromHome              7.0     14.00     29.0  
Education                     3.0      4.00      5.0  
EmployeeCount                 1.0      1.00      1.0  
EnvironmentSatisfaction       3.0      4.00      4.0  
HourlyRate                   66.0     83.00    100.0  
JobInvolvement                3.0      3.00      4.0  
JobLevel                      2.0      3.00      5.0  
JobSatisfaction               3.0      4.00      4.0  
MonthlyIncome              4933.0   8395.00  19999.0  
MonthlyRate               14225.5  20428.25  26999.0  
NumCompaniesWorked            2.0      4.00      9.0  
PercentSalaryHike            14.0     18.00     25.0  
PerformanceRating             3.0      3.00      4.0  
RelationshipSatisfaction      3.0      4.00      4.0  
StandardHours                80.0     80.00     80.0  
StockOptionLevel              1.0      1.00      3.0  
TotalWorkingYears            10.0     15.00     40.0  
TrainingTimesLastYear         3.0      3.00      6.0  
WorkLifeBalance               3.0      3.00      4.0  
YearsAtCompany                5.0      9.00     40.0  
YearsInCurrentRole            3.0      7.00     18.0  
YearsSinceLastPromotion       1.0      3.00     15.0  
YearsWithCurrManager          3.0      7.00     17.0

In [13]:
# check columns with only 1 value
df_stats[df_stats['std'] == 0]

count  mean  std   min   25%   50%   75%   max
EmployeeCount  1370.0   1.0  0.0   1.0   1.0   1.0   1.0   1.0
StandardHours  1370.0  80.0  0.0  80.0  80.0  80.0  80.0  80.0

Columns like 'EmployeeCount' and 'StandardHours' have 0 std, meaning all the values are the same, therefore we can drop them.

In [14]:
# Check target variable
df[target_col].unique()

array(['Yes', 'No'], dtype=object)

# Data process

Numerical cols

In [15]:
from sklearn.preprocessing import MinMaxScaler

def process_numerical_data(df,numerical_cols):
    sacalar = MinMaxScaler()
    df_numerical = sacalar.fit_transform(df[numerical_cols])
    return df_numerical

df_numerical = process_numerical_data(df,numerical_cols)

<img src="https://media.geeksforgeeks.org/wp-content/uploads/min-max-normalisation.jpg">

In [16]:
numerical_cols

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EmployeeCount',
 'EnvironmentSatisfaction',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [17]:
df_numerical[1]

array([0.73809524, 0.12670007, 0.25      , 0.        , 0.        ,
       0.66666667, 0.44285714, 0.33333333, 0.25      , 0.33333333,
       0.21700895, 0.9160008 , 0.11111111, 0.85714286, 1.        ,
       1.        , 0.        , 0.33333333, 0.25      , 0.5       ,
       0.66666667, 0.25      , 0.38888889, 0.06666667, 0.41176471])

Categorical cols

In [18]:
df[categorical_cols]

BusinessTravel              Department EducationField  Gender  \
0         Travel_Rarely                   Sales  Life Sciences  Female   
1     Travel_Frequently  Research & Development  Life Sciences    Male   
2         Travel_Rarely  Research & Development          Other    Male   
3     Travel_Frequently  Research & Development  Life Sciences  Female   
4         Travel_Rarely  Research & Development        Medical    Male   
...                 ...                     ...            ...     ...   
1365  Travel_Frequently  Research & Development        Medical    Male   
1366      Travel_Rarely  Research & Development        Medical    Male   
1367      Travel_Rarely  Research & Development  Life Sciences    Male   
1368  Travel_Frequently                   Sales        Medical    Male   
1369      Travel_Rarely  Research & Development        Medical    Male   

                        JobRole MaritalStatus Over18 OverTime  
0               Sales Executive        Single      Y      Yes  
1            Research Scientist       Married      Y       No  
2         Laboratory Technician        Single      Y      Yes  
3            Research Scientist       Married      Y      Yes  
4         Laboratory Technician       Married      Y       No  
...                         ...           ...    ...      ...  
1365      Laboratory Technician       Married      Y       No  
1366  Healthcare Representative       Married      Y       No  
1367     Manufacturing Director       Married      Y      Yes  
1368            Sales Executive       Married      Y       No  
1369      Laboratory Technician       Married      Y       No  

[1370 rows x 8 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

def process_categorical_data(df,categorical_cols):
    df_categorical = None
    drop_cols = ['EmployeeCount', 'Over18', 'StandardHours']
    
    for col in [var for var in categorical_cols if var not in drop_cols]:
        lbe = LabelEncoder()
        ohe = OneHotEncoder()

        lbe.fit(df[col].values.reshape(-1, 1))
        df[col] = lbe.transform(df[col])

        ohe.fit(df[col].values.reshape(-1, 1))
        oht_df = ohe.transform(df[col].values.reshape(-1, 1)).todense()

        if df_categorical is None:
            df_categorical = oht_df
        else:
            df_categorical = np.hstack((df_categorical, oht_df))
    return df_categorical

In [20]:
df_categorical = process_categorical_data(df,categorical_cols)
df_categorical

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

matrix([[0., 0., 1., ..., 1., 0., 1.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 1., 0., 1.],
        ...,
        [0., 0., 1., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 0., 1., 0.]])

In [21]:
df_numerical

array([[0.54761905, 0.71581961, 0.        , ..., 0.22222222, 0.        ,
        0.29411765],
       [0.73809524, 0.12670007, 0.25      , ..., 0.38888889, 0.06666667,
        0.41176471],
       [0.45238095, 0.90980673, 0.03571429, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.21428571, 0.03793844, 0.10714286, ..., 0.11111111, 0.        ,
        0.17647059],
       [0.73809524, 0.65926986, 0.03571429, ..., 0.33333333, 0.        ,
        0.47058824],
       [0.38095238, 0.37652112, 0.25      , ..., 0.16666667, 0.06666667,
        0.11764706]])

In [22]:
df_numerical.shape, df_categorical.shape

((1370, 25), (1370, 28))

In [23]:
df_features = np.hstack((df_numerical, df_categorical))
df_features.shape

(1370, 53)

Labels

In [24]:
def process_label(df):
    target_col_dict = {'Yes': 1, 'No': 0}
    df_labels = df[target_col].map(target_col_dict).values
    return df_labels
df_labels = process_label(df)
df_labels.shape

(1370,)

# Set Up Model

In [25]:
# split the data into train and test
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(df_features,df_labels, test_size=0.2, random_state=23)

In [26]:
from sklearn import metrics
from sklearn.ensemble import AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.tree import DecisionTreeClassifier

import xgboost as xgb

In [27]:
# Weird solution but give a high prediction:
# KFold and only grab the highest prediction from the batch
# In general: KFold should only be used as validation

rng = np.random.RandomState(31337)

y = df_labels
X = df_features
THRESHOLD = 0.94

kf = KFold(n_splits=20, shuffle=True, random_state=rng)
result = []

for train_index, test_index in kf.split(X):
    xgb_model = xgb.XGBClassifier().fit(X[train_index], y[train_index])
    lr_model = LogisticRegression(random_state=42, max_iter=300).fit(X[train_index], y[train_index])
    mlp_model = MLPClassifier(max_iter=800).fit(X[train_index], y[train_index])
    
    predictions_xgb = xgb_model.predict(X[test_index])
    predictions_lr = lr_model.predict(X[test_index])
    predictions_mlp = mlp_model.predict(X[test_index])
    actuals = y[test_index]
    
    if (metrics.accuracy_score(actuals, predictions_xgb) > THRESHOLD):
        result.append(xgb_model)
        
    if (metrics.accuracy_score(actuals, predictions_lr) > THRESHOLD):   
        result.append(lr_model)
        
    if (metrics.accuracy_score(actuals, predictions_mlp) > THRESHOLD):
        result.append(mlp_model)

In [28]:
from pprint import pprint
pprint(result)

[LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False),
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False),
 XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraint

In [29]:
final = []

for classifier in result:
    final.append(pd.DataFrame(classifier.predict(test_x)))
    print(metrics.accuracy_score(test_y, pd.DataFrame(classifier.predict(test_x))))
    
df = pd.concat(final, axis=1)
new_model_kfold = LogisticRegression()
new_model_kfold.fit(df, test_y)

0.9051094890510949
0.9051094890510949
1.0
0.9963503649635036
0.9014598540145985


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
NN = MLPClassifier(max_iter=200)
RR = RandomForestClassifier()
MNB = MultinomialNB()

model0 = GradientBoostingClassifier(learning_rate=0.01,random_state=1)
model1 = AdaBoostClassifier(random_state=24)
model2 = KNeighborsClassifier(n_neighbors=8, weights="distance")
model3 = LogisticRegression(random_state=42, max_iter=300)
model4 = ExtraTreesClassifier()
model5 = KNeighborsClassifier(n_neighbors=4)
model6 = KNeighborsClassifier(n_neighbors=16)
model7 = xgb.XGBClassifier(random_state=1, learning_rate=0.01)


NN.fit(train_x,train_y)
RR.fit(train_x, train_y)
MNB.fit(train_x, train_y)

model0.fit(train_x, train_y)
model1.fit(train_x, train_y)
model2.fit(train_x, train_y)
model3.fit(train_x, train_y)
model4.fit(train_x, train_y)
model5.fit(train_x, train_y)
model6.fit(train_x, train_y)
model7.fit(train_x, train_y)

# accuracy calculation

y_pred_0 = pd.DataFrame(NN.predict(test_x))
y_pred_1 = pd.DataFrame(RR.predict(test_x))
y_pred_2 = pd.DataFrame(MNB.predict(test_x))
y_pred_3 = pd.DataFrame(model0.predict(test_x))
y_pred_4 = pd.DataFrame(model1.predict(test_x))
y_pred_5 = pd.DataFrame(model2.predict(test_x))
y_pred_6 = pd.DataFrame(model3.predict(test_x))
y_pred_7 = pd.DataFrame(model4.predict(test_x))
y_pred_8 = pd.DataFrame(model5.predict(test_x))
y_pred_9 = pd.DataFrame(model6.predict(test_x))
y_pred_10 = pd.DataFrame(model7.predict(test_x))


print("Accuracy of NN:", metrics.accuracy_score(test_y, y_pred_0))
print("Accuracy of RR:", metrics.accuracy_score(test_y, y_pred_1))
print("Accuracy of MNB:", metrics.accuracy_score(test_y, y_pred_2))
print("Accuracy of GBM:", metrics.accuracy_score(test_y, y_pred_3))
print("Accuracy of ADA:", metrics.accuracy_score(test_y, y_pred_4))
print("Accuracy of KNN:", metrics.accuracy_score(test_y, y_pred_5))
print("Accuracy of LR:", metrics.accuracy_score(test_y, y_pred_6))
print("Accuracy of EXTRA:", metrics.accuracy_score(test_y, y_pred_7))
print("Accuracy of KNN4:", metrics.accuracy_score(test_y, y_pred_8))
print("Accuracy of KNN16:", metrics.accuracy_score(test_y, y_pred_9))
print("Accuracy of XGB:", metrics.accuracy_score(test_y, y_pred_10))

df = pd.concat([y_pred_0, y_pred_1, y_pred_2, y_pred_3, y_pred_4, y_pred_5, y_pred_6, y_pred_7, y_pred_8, y_pred_9, y_pred_10], axis=1)

new_model = LogisticRegression(random_state=42)
new_model.fit(df, test_y)


/usr/local/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Accuracy of NN: 0.8613138686131386
Accuracy of RR: 0.8613138686131386
Accuracy of MNB: 0.864963503649635
Accuracy of GBM: 0.843065693430657
Accuracy of ADA: 0.8686131386861314
Accuracy of KNN: 0.8540145985401459
Accuracy of LR: 0.8795620437956204
Accuracy of EXTRA: 0.8613138686131386
Accuracy of KNN4: 0.8576642335766423
Accuracy of KNN16: 0.8503649635036497
Accuracy of XGB: 0.8613138686131386


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
from statistics import mean
from numpy import std

In [32]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score

# evaluate a give model using cross-validation
def evaluate_model(model):
    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=1)
    scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
    return scores

# get the models to evaluate
models = [NN, RR, MNB, model0, model1, model2, model3, model4, model5, model6, model7]

# evaluate the models and store results
for model in models:
    print(model)
    scores = evaluate_model(model)
    print(scores)
    print('> %.3f (%.3f)' % (mean(scores), std(scores)))
    print("===========================================")
    
    
# ensemble kfold
print(new_model_kfold)
scores = evaluate_model(new_model_kfold)
print(scores)
print('> %.3f (%.3f)' % (mean(scores), std(scores)))
print("===========================================")
    
# ensemble multimodel
print(new_model)
scores = evaluate_model(new_model)
print(scores)
print('> %.3f (%.3f)' % (mean(scores), std(scores)))
print("===========================================")

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)
[0.87226277 0.87226277 0.86131387 0.8649635  0.84671533 0.86131387
 0.86861314 0.86131387 0.86861314 0.83941606 0.85036496 0.8540146
 0.8649635  0.87226277 0.84306569]
> 0.860 (0.011)
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
  

# Make prediction on test data set

In [33]:
df_test = pd.read_csv('HR-Employee-Attrition_test.csv')
df_test

Age     BusinessTravel  DailyRate              Department  \
0    31      Travel_Rarely       1112                   Sales   
1    31      Travel_Rarely       1154                   Sales   
2    32  Travel_Frequently        379                   Sales   
3    42      Travel_Rarely        188  Research & Development   
4    23      Travel_Rarely        373  Research & Development   
..  ...                ...        ...                     ...   
95   32  Travel_Frequently        689                   Sales   
96   38      Travel_Rarely        330  Research & Development   
97   44      Travel_Rarely       1037  Research & Development   
98   37      Travel_Rarely        671  Research & Development   
99   58      Travel_Rarely        286  Research & Development   

    DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                  5          4  Life Sciences              1            1673   
1                  2          2  Life Sciences              1            1996   
2                  5          2  Life Sciences              1             889   
3                 29          3        Medical              1            1148   
4                  1          2  Life Sciences              1            1270   
..               ...        ...            ...            ...             ...   
95                 9          2        Medical              1             195   
96                17          1  Life Sciences              1            1088   
97                 1          3        Medical              1            2020   
98                19          3  Life Sciences              1            1631   
99                 2          4  Life Sciences              1             825   

    EnvironmentSatisfaction  ... RelationshipSatisfaction  StandardHours  \
0                         1  ...                        1             80   
1                         1  ...                        3             80   
2                         2  ...                        4             80   
3                         2  ...                        1             80   
4                         4  ...                        4             80   
..                      ...  ...                      ...            ...   
95                        4  ...                        4             80   
96                        3  ...                        1             80   
97                        2  ...                        3             80   
98                        3  ...                        1             80   
99                        4  ...                        4             80   

    StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0                  2                 10                     2   
1                  1                  3                     1   
2                  1                 10                     3   
3                  0                 16                     3   
4                  1                  1                     2   
..               ...                ...                   ...   
95                 3                  9                     2   
96                 1                 20                     4   
97                 0                  6                     2   
98                 3                  9                     2   
99                 0                 40                     2   

    WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                 3             10                   0   
1                 3              2                   2   
2                 3             10                   8   
3                 3              1                   0   
4                 3              1                   0   
..              ...            ...                 ...   
95                4              8                   7   
96                2             19                   9   
97                3              4

In [34]:
df_numerical_test = process_numerical_data(df_test,numerical_cols)
df_categorical_test = process_categorical_data(df_test,categorical_cols)
df_features_test = np.hstack((df_numerical_test, df_categorical_test))
df_features_test

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

matrix([[0.325     , 0.72469046, 0.14285714, ..., 0.        , 1.        ,
         0.        ],
        [0.325     , 0.75528041, 0.03571429, ..., 0.        , 1.        ,
         0.        ],
        [0.35      , 0.19082302, 0.14285714, ..., 0.        , 1.        ,
         0.        ],
        ...,
        [0.65      , 0.67006555, 0.        , ..., 1.        , 0.        ,
         1.        ],
        [0.475     , 0.40349599, 0.64285714, ..., 0.        , 1.        ,
         0.        ],
        [1.        , 0.12308813, 0.03571429, ..., 1.        , 0.        ,
         1.        ]])

In [35]:
# accuracy calculation
y_pred_0 = pd.DataFrame(NN.predict(df_features_test))
y_pred_1 = pd.DataFrame(RR.predict(df_features_test))
y_pred_2 = pd.DataFrame(MNB.predict(df_features_test))
y_pred_3 = pd.DataFrame(model0.predict(df_features_test))
y_pred_4 = pd.DataFrame(model1.predict(df_features_test))
y_pred_5 = pd.DataFrame(model2.predict(df_features_test))
y_pred_6 = pd.DataFrame(model3.predict(df_features_test))
y_pred_7 = pd.DataFrame(model4.predict(df_features_test))
y_pred_8 = pd.DataFrame(model5.predict(df_features_test))
y_pred_9 = pd.DataFrame(model6.predict(df_features_test))
y_pred_10 = pd.DataFrame(model7.predict(df_features_test))

real_test_df = pd.concat([y_pred_0, y_pred_1, y_pred_2, y_pred_3, y_pred_4, y_pred_5, y_pred_6, y_pred_7, y_pred_8, y_pred_9, y_pred_10], axis=1)


In [36]:
predicted_test = new_model.predict(real_test_df)
predicted_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [37]:
final_test = []

for classifier in result:
    final_test.append(pd.DataFrame(classifier.predict(df_features_test)))
    
super_df = pd.concat(final_test, axis=1)
predicted_test = new_model_kfold.predict(super_df)
predicted_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [38]:
predicted_test_proba = NN.predict_proba(df_features_test)
predicted_test_proba

array([[8.02994973e-01, 1.97005027e-01],
       [9.73968469e-01, 2.60315314e-02],
       [8.36807667e-01, 1.63192333e-01],
       [1.38552701e-01, 8.61447299e-01],
       [9.93326303e-01, 6.67369739e-03],
       [9.99154708e-01, 8.45292223e-04],
       [9.10514367e-01, 8.94856331e-02],
       [9.81777747e-01, 1.82222528e-02],
       [9.46281070e-01, 5.37189300e-02],
       [7.91540279e-01, 2.08459721e-01],
       [7.65221585e-01, 2.34778415e-01],
       [9.98790362e-01, 1.20963842e-03],
       [9.59386781e-01, 4.06132194e-02],
       [9.61210927e-01, 3.87890726e-02],
       [9.98467819e-01, 1.53218121e-03],
       [9.37829720e-01, 6.21702800e-02],
       [9.99569843e-01, 4.30156600e-04],
       [9.79061249e-01, 2.09387508e-02],
       [9.97371862e-01, 2.62813845e-03],
       [4.45431990e-01, 5.54568010e-01],
       [3.45764934e-01, 6.54235066e-01],
       [4.83487080e-01, 5.16512920e-01],
       [9.97461546e-01, 2.53845445e-03],
       [7.61208577e-01, 2.38791423e-01],
       [9.763436

In [39]:
predicted_test_proba[:,1]

array([1.97005027e-01, 2.60315314e-02, 1.63192333e-01, 8.61447299e-01,
       6.67369739e-03, 8.45292223e-04, 8.94856331e-02, 1.82222528e-02,
       5.37189300e-02, 2.08459721e-01, 2.34778415e-01, 1.20963842e-03,
       4.06132194e-02, 3.87890726e-02, 1.53218121e-03, 6.21702800e-02,
       4.30156600e-04, 2.09387508e-02, 2.62813845e-03, 5.54568010e-01,
       6.54235066e-01, 5.16512920e-01, 2.53845445e-03, 2.38791423e-01,
       2.36563199e-02, 2.36082685e-03, 1.55282536e-03, 1.54287290e-06,
       2.40764389e-02, 2.48223966e-02, 2.91144058e-04, 1.64718744e-01,
       1.19521288e-02, 6.44244427e-03, 4.44286379e-02, 2.02377373e-02,
       1.49847698e-03, 3.99548436e-06, 2.79355421e-02, 2.88112947e-02,
       5.05840586e-03, 1.08524257e-01, 6.84799214e-02, 8.00615826e-02,
       1.36950893e-02, 5.74880380e-02, 3.05670553e-02, 7.21779982e-02,
       1.25584382e-02, 1.11211749e-01, 1.02241785e-01, 4.09403227e-03,
       6.56922610e-02, 9.97727202e-01, 1.07396351e-02, 6.70571507e-03,
      

# GridSearch to find the optimal parameter setting

Most used parameter

1）The ith element represents the number of neurons in the ith hidden layer.
    example: hidden_layer_sizes=(10)

2）activation function
    example: activation="relu"

3）The solver for weight optimization. {'lbfgs', 'sgd', 'adam'}
    example: solver='adam'

4）L2 penalty (regularization term) parameter
    example: alpha=0.0001

5）Size of minibatches for stochastic optimizers.
    If the solver is 'lbfgs', the classifier will not use minibatch.
    When set to "auto", `batch_size=min(200, n_samples)`
    example: batch_size='auto'

6）Learning rate schedule for weight updates.
    example: learning_rate="constant"

7）The initial learning rate used. It controls the step-size
    in updating the weights. Only used when solver='sgd' or 'adam'.
    example: learning_rate_init=0.001

8）Maximum number of iterations. The solver iterates until convergence
    example: max_iter=200

9）Tolerance for the optimization. When the loss or score is not improving
    by at least ``tol`` for ``n_iter_no_change`` consecutive iterations,
    unless ``learning_rate`` is set to 'adaptive', convergence is
    considered to be reached and training stops.
    example: tol=1e-4

In [40]:
import time
start_time = time.time()
NN_new = MLPClassifier(max_iter=1000)
parameter_space = {
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (50,100,50,25)],
    'activation': ['tanh', 'relu','logistic'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.001, 0.01],
    'learning_rate': ['constant','adaptive'],
}
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(NN_new, parameter_space, n_jobs=-1, cv=10)
clf.fit(train_x, train_y)
print('Time taken for training the model: '+ str(time.time() - start_time))

Time taken for training the model: 355.3855171203613


In [41]:
# Best paramete set
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'activation': 'logistic', 'alpha': 0.01, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'adam'}


In [42]:
# All results
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))

0.829 (+/-0.045) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'adam'}
0.834 (+/-0.035) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'lbfgs'}
0.820 (+/-0.054) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.817 (+/-0.087) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'adaptive', 'solver': 'lbfgs'}
0.828 (+/-0.056) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'adam'}
0.822 (+/-0.050) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'lbfgs'}
0.826 (+/-0.039) for {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'adaptive', 'solver': '

In [43]:
y_true, y_pred = test_y , clf.predict(test_x)
from sklearn.metrics import classification_report
print('Results on the test set:')
print(classification_report(y_true, y_pred))

Results on the test set:
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       229
           1       0.81      0.58      0.68        45

    accuracy                           0.91       274
   macro avg       0.87      0.78      0.81       274
weighted avg       0.90      0.91      0.90       274



In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.9087591240875912

In [45]:
# only 91% accurate
clf.predict(df_features_test)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [46]:
list(predicted_test).count(1)

5

In [47]:
new_predicted_test = []

for i in predicted_test:
    if (i == 0):
        new_predicted_test.append("No")
    else:
        new_predicted_test.append("Yes")

In [48]:
new_pd = pd.DataFrame()
new_pd["EmployeeNumber"] = df_test["EmployeeNumber"]
new_pd["Attrition"] = new_predicted_test
new_pd

EmployeeNumber Attrition
0             1673        No
1             1996        No
2              889        No
3             1148        No
4             1270        No
..             ...       ...
95             195        No
96            1088        No
97            2020        No
98            1631        No
99             825        No

[100 rows x 2 columns]

In [49]:
new_pd.to_csv('Updated2.csv', index=False)